patch for getdistreader
williamjameshandley/anesthetic pull request #172
Opened 2021-07-07 09:04 UTC by lukashergt

This addresses #171, which seems to suggest that anesthetic is behind GetDist, assuming the second column in the output format to be `chi2` when it really is `-logL`.

Fixes #171 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My code is PEP8 compliant (`flake8 anesthetic tests`)
- [ ] My code contains compliant docstrings (`pydocstyle --convention=numpy anesthetic`)
- [ ] New and existing unit tests pass locally with my changes (`python -m pytest`)
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-07-14 10:58 UTC, williamjameshandley requested changes
If this is indeed the default column for getdist, then this looks like all we need. 

However, in order to really isolate this, I think that the best way to prove we've fixed it is to create some explicit tests which load our test files in `tests/example_data/gd.txt` using getdist, and explicitly compares them.

We should ideally also make sure that the example getdist is in the new format (e.g. using -logL rather than chi2).

This is also the appropriate PR to do the same for cobaya and montepython chain reading

2021-07-14 22:24 UTC, lukashergt commented
> However, in order to really isolate this, I think that the best way to prove we've fixed it is to create some explicit tests which load our test files in `tests/example_data/gd.txt` using getdist, and explicitly compares them.

Good idea, currently there is a sign difference between getdist and anesthetic when loading the `tests/example_data/gd*` data, which means that either the data is outdated or there is some inconsistency with the getdist documentation (according to the getdist docs the second column should be `-log(L)` which is how I treat it in this PR).
&nbsp;

> We should ideally also make sure that the example getdist is in the new format (e.g. using -logL rather than chi2).

The `tests/example_data/gd*` files indeed seem to be out of date. I expect they were generated using CosmoMC? Could you generate and push new ones, @williamjameshandley?
&nbsp;

> This is also the appropriate PR to do the same for cobaya and montepython chain reading

Yes, I'll start this once #167 is merged.

2021-07-15 06:56 UTC, lukashergt commented on tests/test_reader.py
> +    assert_array_almost_equal(mcmc.logL, mcmc_gd.loglikes, decimal=15)
This type of tests works with the new `cobayamcmcreader` and the `cb` example data, but it does _not_ currently work with the `getdistreader` and the `gd` example data.

2021-07-15 07:57 UTC, williamjameshandley commented
> The `tests/example_data/gd*` files indeed seem to be out of date. I expect they were generated using CosmoMC? Could you generate and push new ones, @williamjameshandley?

Done in 706a6bc, and updated the automatic generation script.

2021-09-01 11:26 UTC, williamjameshandley approved these changes
Many thanks @lukashergt I added a couple of changes to increase the coverage around this portion of code, as well as a removal of a couple of redundant (untested) lines associated with python2 compatibility. If you're happy with these please squash and merge.

2021-09-07 14:00 UTC, lukashergt commented
This is on my to-do list, but I first want to verify that the new CosmoMC behaviour is indeed to put `-logL` in the second column. Since the new `gd.txt` data was generated with anesthetic's `gen_data.py` and not with CosmoMC itself, we should double check this manually.

2021-09-07 23:31 UTC, lukashergt commented
Ok, I checked with CosmoMC, the second column indeed should be `-logL`, so this PR should take care of that.

2021-09-07 23:33 UTC, lukashergt commented on tests/test_reader.py
> +    assert_array_almost_equal(mcmc.logL, mcmc_gd.loglikes, decimal=15)
fixed with new example data

2021-09-08 06:15 UTC, williamjameshandley approved these changes
Many thanks @lukashergt

2021-09-08 07:06 UTC, merged